version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: capybara-db
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: capybara-db
